dist: xenial
language: python
cache: pip

services:
  - docker

env:
  global:
    - AGENT_VERSION="0.2.100"

install:
  # Install Pennsieve CLI agent
  - wget "https://github.com/Pennsieve/agent/releases/download/${AGENT_VERSION}/pennsieve_${AGENT_VERSION}_amd64.deb" -O agent.deb
  - sudo dpkg -i agent.deb
  - which pennsieve
  - which openssl
  - openssl version -a
  - wget https://www.openssl.org/source/old/1.1.0/openssl-1.1.0g.tar.gz
  - tar xzvf openssl-1.1.0g.tar.gz
  - cd openssl-1.1.0g
  - ./config  --prefix=/usr
  - make
  - sudo make install
  - which openssl
  - openssl version -a
  - pennsieve version

  # Give agent permissions to home dir because of AP-548
  - sudo chown -R $USER:$USER $HOME/.pennsieve

  - pip install --upgrade pip setuptools wheel
  - pip install .
  - pip install --upgrade -r requirements-test.txt


script: pytest
after_success: bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: lint
      python: 3.6
      script:
        - pip install -r requirements-format.txt
        - make lint

    - stage: test Python 2.7
      python: 2.7

    - stage: test Python 3.5
      python: 3.5

    - stage: test Python 3.8
      python: 3.8
      dist: xenial

    - stage: docs
      python: 3.6
      script:
        - cd docs
        - make install
        - make html
        - make html-latest
        - cd $TRAVIS_BUILD_DIR
      deploy:
        provider: s3
        on:
          tags: true
          all_branches: true
        access_key_id: "$AWS_ACCESS_KEY_ID"
        secret_access_key: "$AWS_SECRET_ACCESS_KEY"
        bucket: "$S3_BUCKET_DOCS"
        skip_cleanup: true
        region: us-east-1
        local_dir: docs/_build/html
        upload-dir: python
        acl: public_read

    - stage: release
      if: tag IS present
      python: '3.6'
      install: skip
      script: skip
      deploy:
        - provider: pypi
          on:
            all_branches: true
          user: pennsieve
          password: "$PYPI_PASSWORD"
          #server: https://test.pypi.org/legacy/ # uncomment to use test pypi
          distributions: sdist bdist_wheel
        - provider: script
          on:
            all_branches: true
          script: bash bin/docker_push.sh "$TRAVIS_TAG"

notifications:
  slack:
    secure: X1xWT7VNg8FB5i8ze65lckyMz/BXKAvftyK27HdSempXw+SOle/wSo2Om+6I52pl2UDxncYBspTFYs65A2mEpWXMVJdF6WIp4tYf+MzgpAQf2vMCi04YqMY22LaqVkwwuk6fVFjQ6lp4tZtwWoW3hjat1FD9E9f/sK3nH5bu8zRvnq6gseqkAEOu87U58FcL4mSjkigU36LulQUFEsSCDIzEmMng6CExMsjj3YLaYJu4S5N8viRl3iOUs6ksCzkwvM9V5+eOJ4K+y2wu/0GlDBgrGHjYPOojCV5hXOj3oAAAGuW+T+BM2mx5YPXqL7VNKOkiHsxzASwIExqDE3Tr+Z/L1+5b2LR0LZWU02aGbSsXjgTroShdKOkvsQlHMo7NaVBypGMVET7+zMTdwCqj2AZrIN6+k0PuqILnZBvMXeGePZYCxSOFsUczSq2jeh/DivW6ZAGHa5D/5UXCpAh88bzbnNnMai+gxjN/sYFqhDciXZBRvGi5NQBOwZdZf447O3ZreS2XJhDXxnbNduy1xMWOR82cDYlyqz+64QDzemoDs6P2tD/i/qs34iZSpgIWjjoMbx8kQxHsvOBBYDPifNW5mUPyduqs5S3VSqc+Fy6xk9yfxrN8U40Q/poqp7WEXG3cllL1/wgh2zGRk4boCymxUkFJoKhX8bPZvYPaJDU=
